package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for settopologicalchargelattice kernel
var settopologicalchargelattice_code cu.Function

// Stores the arguments for settopologicalchargelattice kernel invocation
type settopologicalchargelattice_args_t struct {
	arg_s     unsafe.Pointer
	arg_mx    unsafe.Pointer
	arg_my    unsafe.Pointer
	arg_mz    unsafe.Pointer
	arg_icxcy float32
	arg_Nx    int
	arg_Ny    int
	arg_Nz    int
	arg_PBC   byte
	argptr    [9]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for settopologicalchargelattice kernel invocation
var settopologicalchargelattice_args settopologicalchargelattice_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	settopologicalchargelattice_args.argptr[0] = unsafe.Pointer(&settopologicalchargelattice_args.arg_s)
	settopologicalchargelattice_args.argptr[1] = unsafe.Pointer(&settopologicalchargelattice_args.arg_mx)
	settopologicalchargelattice_args.argptr[2] = unsafe.Pointer(&settopologicalchargelattice_args.arg_my)
	settopologicalchargelattice_args.argptr[3] = unsafe.Pointer(&settopologicalchargelattice_args.arg_mz)
	settopologicalchargelattice_args.argptr[4] = unsafe.Pointer(&settopologicalchargelattice_args.arg_icxcy)
	settopologicalchargelattice_args.argptr[5] = unsafe.Pointer(&settopologicalchargelattice_args.arg_Nx)
	settopologicalchargelattice_args.argptr[6] = unsafe.Pointer(&settopologicalchargelattice_args.arg_Ny)
	settopologicalchargelattice_args.argptr[7] = unsafe.Pointer(&settopologicalchargelattice_args.arg_Nz)
	settopologicalchargelattice_args.argptr[8] = unsafe.Pointer(&settopologicalchargelattice_args.arg_PBC)
}

// Wrapper for settopologicalchargelattice CUDA kernel, asynchronous.
func k_settopologicalchargelattice_async(s unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, icxcy float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("settopologicalchargelattice")
	}

	settopologicalchargelattice_args.Lock()
	defer settopologicalchargelattice_args.Unlock()

	if settopologicalchargelattice_code == 0 {
		settopologicalchargelattice_code = fatbinLoad(settopologicalchargelattice_map, "settopologicalchargelattice")
	}

	settopologicalchargelattice_args.arg_s = s
	settopologicalchargelattice_args.arg_mx = mx
	settopologicalchargelattice_args.arg_my = my
	settopologicalchargelattice_args.arg_mz = mz
	settopologicalchargelattice_args.arg_icxcy = icxcy
	settopologicalchargelattice_args.arg_Nx = Nx
	settopologicalchargelattice_args.arg_Ny = Ny
	settopologicalchargelattice_args.arg_Nz = Nz
	settopologicalchargelattice_args.arg_PBC = PBC

	args := settopologicalchargelattice_args.argptr[:]
	cu.LaunchKernel(settopologicalchargelattice_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("settopologicalchargelattice")
	}
}

// maps compute capability on PTX code for settopologicalchargelattice kernel.
var settopologicalchargelattice_map = map[int]string{0: "",
	30: settopologicalchargelattice_ptx_30}

// settopologicalchargelattice PTX code for various compute capabilities.
const (
	settopologicalchargelattice_ptx_30 = `
.version 6.4
.target sm_30
.address_size 64

	// .globl	settopologicalchargelattice

.visible .entry settopologicalchargelattice(
	.param .u64 settopologicalchargelattice_param_0,
	.param .u64 settopologicalchargelattice_param_1,
	.param .u64 settopologicalchargelattice_param_2,
	.param .u64 settopologicalchargelattice_param_3,
	.param .f32 settopologicalchargelattice_param_4,
	.param .u32 settopologicalchargelattice_param_5,
	.param .u32 settopologicalchargelattice_param_6,
	.param .u32 settopologicalchargelattice_param_7,
	.param .u8 settopologicalchargelattice_param_8
)
{
	.reg .pred 	%p<88>;
	.reg .b16 	%rs<23>;
	.reg .f32 	%f<295>;
	.reg .b32 	%r<311>;
	.reg .b64 	%rd<61>;


	ld.param.u64 	%rd5, [settopologicalchargelattice_param_0];
	ld.param.u64 	%rd6, [settopologicalchargelattice_param_1];
	ld.param.u64 	%rd7, [settopologicalchargelattice_param_2];
	ld.param.u64 	%rd8, [settopologicalchargelattice_param_3];
	ld.param.f32 	%f52, [settopologicalchargelattice_param_4];
	ld.param.u32 	%r57, [settopologicalchargelattice_param_5];
	ld.param.u32 	%r58, [settopologicalchargelattice_param_6];
	ld.param.u32 	%r59, [settopologicalchargelattice_param_7];
	ld.param.u8 	%rs3, [settopologicalchargelattice_param_8];
	cvta.to.global.u64 	%rd1, %rd8;
	cvta.to.global.u64 	%rd2, %rd7;
	cvta.to.global.u64 	%rd3, %rd6;
	mov.u32 	%r60, %ntid.x;
	mov.u32 	%r61, %ctaid.x;
	mov.u32 	%r62, %tid.x;
	mad.lo.s32 	%r1, %r60, %r61, %r62;
	mov.u32 	%r63, %ntid.y;
	mov.u32 	%r64, %ctaid.y;
	mov.u32 	%r65, %tid.y;
	mad.lo.s32 	%r2, %r63, %r64, %r65;
	mov.u32 	%r66, %ntid.z;
	mov.u32 	%r67, %ctaid.z;
	mov.u32 	%r68, %tid.z;
	mad.lo.s32 	%r3, %r66, %r67, %r68;
	setp.ge.s32	%p2, %r2, %r58;
	setp.ge.s32	%p3, %r1, %r57;
	or.pred  	%p4, %p2, %p3;
	setp.ge.s32	%p5, %r3, %r59;
	or.pred  	%p6, %p4, %p5;
	@%p6 bra 	BB0_72;

	cvta.to.global.u64 	%rd9, %rd5;
	mul.lo.s32 	%r4, %r3, %r58;
	add.s32 	%r69, %r4, %r2;
	mul.lo.s32 	%r5, %r69, %r57;
	add.s32 	%r70, %r5, %r1;
	mul.wide.s32 	%rd10, %r70, 4;
	add.s64 	%rd11, %rd3, %rd10;
	add.s64 	%rd12, %rd2, %rd10;
	add.s64 	%rd13, %rd1, %rd10;
	ld.global.f32 	%f1, [%rd11];
	ld.global.f32 	%f2, [%rd12];
	mul.f32 	%f53, %f2, %f2;
	fma.rn.f32 	%f54, %f1, %f1, %f53;
	ld.global.f32 	%f3, [%rd13];
	fma.rn.f32 	%f55, %f3, %f3, %f54;
	setp.eq.f32	%p7, %f55, 0f00000000;
	add.s64 	%rd4, %rd9, %rd10;
	@%p7 bra 	BB0_71;
	bra.uni 	BB0_2;

BB0_71:
	mov.u32 	%r298, 0;
	st.global.u32 	[%rd4], %r298;
	bra.uni 	BB0_72;

BB0_2:
	and.b16  	%rs1, %rs3, 1;
	setp.eq.s16	%p8, %rs1, 0;
	add.s32 	%r6, %r1, 1;
	@%p8 bra 	BB0_4;

	rem.s32 	%r71, %r6, %r57;
	add.s32 	%r72, %r71, %r57;
	rem.s32 	%r299, %r72, %r57;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r73, %r57, -1;
	min.s32 	%r299, %r6, %r73;

BB0_5:
	and.b16  	%rs2, %rs3, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r10, %r2, 1;
	@%p9 bra 	BB0_7;

	rem.s32 	%r74, %r10, %r58;
	add.s32 	%r75, %r74, %r58;
	rem.s32 	%r300, %r75, %r58;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r76, %r58, -1;
	min.s32 	%r300, %r10, %r76;

BB0_8:
	add.s32 	%r14, %r1, -1;
	@%p8 bra 	BB0_10;

	rem.s32 	%r77, %r14, %r57;
	add.s32 	%r78, %r77, %r57;
	rem.s32 	%r301, %r78, %r57;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r79, 0;
	max.s32 	%r301, %r14, %r79;

BB0_11:
	add.s32 	%r18, %r299, %r5;
	add.s32 	%r80, %r300, %r4;
	mad.lo.s32 	%r19, %r80, %r57, %r1;
	add.s32 	%r20, %r301, %r5;
	add.s32 	%r21, %r2, -1;
	@%p9 bra 	BB0_13;

	rem.s32 	%r81, %r21, %r58;
	add.s32 	%r82, %r81, %r58;
	rem.s32 	%r302, %r82, %r58;
	bra.uni 	BB0_14;

BB0_13:
	mov.u32 	%r83, 0;
	max.s32 	%r302, %r21, %r83;

BB0_14:
	add.s32 	%r84, %r302, %r4;
	mad.lo.s32 	%r85, %r84, %r57, %r1;
	mul.wide.s32 	%rd14, %r18, 4;
	add.s64 	%rd15, %rd3, %rd14;
	ld.global.f32 	%f4, [%rd15];
	add.s64 	%rd16, %rd2, %rd14;
	ld.global.f32 	%f5, [%rd16];
	add.s64 	%rd17, %rd1, %rd14;
	ld.global.f32 	%f6, [%rd17];
	mul.wide.s32 	%rd18, %r19, 4;
	add.s64 	%rd19, %rd3, %rd18;
	ld.global.f32 	%f7, [%rd19];
	add.s64 	%rd20, %rd2, %rd18;
	ld.global.f32 	%f8, [%rd20];
	add.s64 	%rd21, %rd1, %rd18;
	ld.global.f32 	%f9, [%rd21];
	mul.wide.s32 	%rd22, %r20, 4;
	add.s64 	%rd23, %rd3, %rd22;
	ld.global.f32 	%f10, [%rd23];
	add.s64 	%rd24, %rd2, %rd22;
	ld.global.f32 	%f11, [%rd24];
	add.s64 	%rd25, %rd1, %rd22;
	ld.global.f32 	%f12, [%rd25];
	mul.wide.s32 	%rd26, %r85, 4;
	add.s64 	%rd27, %rd3, %rd26;
	ld.global.f32 	%f13, [%rd27];
	add.s64 	%rd28, %rd2, %rd26;
	ld.global.f32 	%f14, [%rd28];
	add.s64 	%rd29, %rd1, %rd26;
	ld.global.f32 	%f15, [%rd29];
	setp.ge.s32	%p13, %r6, %r57;
	mov.f32 	%f290, 0f00000000;
	and.pred  	%p14, %p13, %p8;
	@%p14 bra 	BB0_28;

	setp.ge.s32	%p15, %r10, %r58;
	shr.u16 	%rs5, %rs3, 1;
	and.b16  	%rs6, %rs5, 1;
	setp.eq.b16	%p16, %rs6, 1;
	not.pred 	%p17, %p16;
	and.pred  	%p18, %p15, %p17;
	@%p18 bra 	BB0_28;

	@%p9 bra 	BB0_18;

	rem.s32 	%r96, %r10, %r58;
	add.s32 	%r97, %r96, %r58;
	rem.s32 	%r303, %r97, %r58;
	bra.uni 	BB0_19;

BB0_18:
	add.s32 	%r98, %r58, -1;
	min.s32 	%r303, %r10, %r98;

BB0_19:
	setp.eq.b16	%p20, %rs1, 1;
	@!%p20 bra 	BB0_21;
	bra.uni 	BB0_20;

BB0_20:
	rem.s32 	%r109, %r6, %r57;
	add.s32 	%r110, %r109, %r57;
	rem.s32 	%r304, %r110, %r57;
	bra.uni 	BB0_22;

BB0_21:
	add.s32 	%r111, %r57, -1;
	min.s32 	%r304, %r6, %r111;

BB0_22:
	mad.lo.s32 	%r121, %r3, %r58, %r303;
	mad.lo.s32 	%r122, %r121, %r57, %r304;
	mul.wide.s32 	%rd31, %r122, 4;
	add.s64 	%rd32, %rd3, %rd31;
	add.s64 	%rd34, %rd2, %rd31;
	add.s64 	%rd36, %rd1, %rd31;
	ld.global.f32 	%f58, [%rd32];
	ld.global.f32 	%f59, [%rd34];
	mul.f32 	%f60, %f59, %f59;
	fma.rn.f32 	%f61, %f58, %f58, %f60;
	ld.global.f32 	%f62, [%rd36];
	fma.rn.f32 	%f16, %f62, %f62, %f61;
	mul.f32 	%f63, %f6, %f8;
	mul.f32 	%f64, %f5, %f9;
	sub.f32 	%f65, %f64, %f63;
	mul.f32 	%f66, %f4, %f9;
	mul.f32 	%f67, %f6, %f7;
	sub.f32 	%f68, %f67, %f66;
	mul.f32 	%f69, %f5, %f7;
	mul.f32 	%f70, %f4, %f8;
	sub.f32 	%f71, %f70, %f69;
	mul.f32 	%f72, %f2, %f68;
	fma.rn.f32 	%f73, %f1, %f65, %f72;
	fma.rn.f32 	%f74, %f3, %f71, %f73;
	mul.f32 	%f75, %f2, %f5;
	fma.rn.f32 	%f76, %f1, %f4, %f75;
	fma.rn.f32 	%f77, %f3, %f6, %f76;
	add.f32 	%f78, %f77, 0f3F800000;
	mul.f32 	%f79, %f2, %f8;
	fma.rn.f32 	%f80, %f1, %f7, %f79;
	fma.rn.f32 	%f81, %f3, %f9, %f80;
	add.f32 	%f82, %f78, %f81;
	mul.f32 	%f83, %f5, %f8;
	fma.rn.f32 	%f84, %f4, %f7, %f83;
	fma.rn.f32 	%f85, %f6, %f9, %f84;
	add.f32 	%f86, %f85, %f82;
	abs.f32 	%f17, %f86;
	abs.f32 	%f18, %f74;
	setp.eq.f32	%p21, %f17, 0f00000000;
	setp.eq.f32	%p22, %f18, 0f00000000;
	and.pred  	%p23, %p21, %p22;
	mov.b32 	 %r31, %f86;
	mov.b32 	 %r123, %f74;
	and.b32  	%r32, %r123, -2147483648;
	@%p23 bra 	BB0_26;
	bra.uni 	BB0_23;

BB0_26:
	shr.s32 	%r130, %r31, 31;
	and.b32  	%r131, %r130, 1078530011;
	or.b32  	%r132, %r131, %r32;
	mov.b32 	 %f287, %r132;
	bra.uni 	BB0_27;

BB0_23:
	setp.eq.f32	%p24, %f17, 0f7F800000;
	setp.eq.f32	%p25, %f18, 0f7F800000;
	and.pred  	%p26, %p24, %p25;
	@%p26 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	shr.s32 	%r126, %r31, 31;
	and.b32  	%r127, %r126, 13483017;
	add.s32 	%r128, %r127, 1061752795;
	or.b32  	%r129, %r128, %r32;
	mov.b32 	 %f287, %r129;
	bra.uni 	BB0_27;

BB0_24:
	max.f32 	%f87, %f18, %f17;
	min.f32 	%f88, %f18, %f17;
	div.rn.f32 	%f89, %f88, %f87;
	mul.rn.f32 	%f90, %f89, %f89;
	mov.f32 	%f91, 0fC0B59883;
	mov.f32 	%f92, 0fBF52C7EA;
	fma.rn.f32 	%f93, %f90, %f92, %f91;
	mov.f32 	%f94, 0fC0D21907;
	fma.rn.f32 	%f95, %f93, %f90, %f94;
	mul.f32 	%f96, %f90, %f95;
	mul.f32 	%f97, %f89, %f96;
	add.f32 	%f98, %f90, 0f41355DC0;
	mov.f32 	%f99, 0f41E6BD60;
	fma.rn.f32 	%f100, %f98, %f90, %f99;
	mov.f32 	%f101, 0f419D92C8;
	fma.rn.f32 	%f102, %f100, %f90, %f101;
	rcp.rn.f32 	%f103, %f102;
	fma.rn.f32 	%f104, %f97, %f103, %f89;
	mov.f32 	%f105, 0f3FC90FDB;
	sub.f32 	%f106, %f105, %f104;
	setp.gt.f32	%p27, %f18, %f17;
	selp.f32	%f107, %f106, %f104, %p27;
	mov.f32 	%f108, 0f40490FDB;
	sub.f32 	%f109, %f108, %f107;
	setp.lt.s32	%p28, %r31, 0;
	selp.f32	%f110, %f109, %f107, %p28;
	mov.b32 	 %r124, %f110;
	or.b32  	%r125, %r124, %r32;
	mov.b32 	 %f111, %r125;
	add.f32 	%f112, %f17, %f18;
	setp.gtu.f32	%p29, %f112, 0f7F800000;
	selp.f32	%f287, %f112, %f111, %p29;

BB0_27:
	add.f32 	%f113, %f287, %f287;
	setp.eq.f32	%p30, %f16, 0f00000000;
	selp.f32	%f114, 0f3F800000, 0f3F000000, %p30;
	fma.rn.f32 	%f290, %f114, %f113, 0f00000000;

BB0_28:
	setp.eq.b16	%p31, %rs1, 1;
	not.pred 	%p32, %p31;
	setp.lt.s32	%p33, %r14, 0;
	setp.gt.s32	%p34, %r14, -1;
	or.pred  	%p1, %p34, %p31;
	and.pred  	%p35, %p33, %p32;
	@%p35 bra 	BB0_42;

	setp.ge.s32	%p36, %r10, %r58;
	shr.u16 	%rs10, %rs3, 1;
	and.b16  	%rs11, %rs10, 1;
	setp.eq.b16	%p37, %rs11, 1;
	not.pred 	%p38, %p37;
	and.pred  	%p39, %p36, %p38;
	@%p39 bra 	BB0_42;

	@%p9 bra 	BB0_32;

	rem.s32 	%r148, %r10, %r58;
	add.s32 	%r149, %r148, %r58;
	rem.s32 	%r305, %r149, %r58;
	bra.uni 	BB0_33;

BB0_32:
	add.s32 	%r150, %r58, -1;
	min.s32 	%r305, %r10, %r150;

BB0_33:
	setp.eq.b16	%p41, %rs1, 1;
	@!%p41 bra 	BB0_35;
	bra.uni 	BB0_34;

BB0_34:
	rem.s32 	%r161, %r14, %r57;
	add.s32 	%r162, %r161, %r57;
	rem.s32 	%r306, %r162, %r57;
	bra.uni 	BB0_36;

BB0_35:
	mov.u32 	%r168, 0;
	max.s32 	%r306, %r14, %r168;

BB0_36:
	mad.lo.s32 	%r173, %r3, %r58, %r305;
	mad.lo.s32 	%r174, %r173, %r57, %r306;
	mul.wide.s32 	%rd38, %r174, 4;
	add.s64 	%rd39, %rd3, %rd38;
	add.s64 	%rd41, %rd2, %rd38;
	add.s64 	%rd43, %rd1, %rd38;
	ld.global.f32 	%f115, [%rd39];
	ld.global.f32 	%f116, [%rd41];
	mul.f32 	%f117, %f116, %f116;
	fma.rn.f32 	%f118, %f115, %f115, %f117;
	ld.global.f32 	%f119, [%rd43];
	fma.rn.f32 	%f25, %f119, %f119, %f118;
	mul.f32 	%f120, %f9, %f11;
	mul.f32 	%f121, %f8, %f12;
	sub.f32 	%f122, %f121, %f120;
	mul.f32 	%f123, %f7, %f12;
	mul.f32 	%f124, %f9, %f10;
	sub.f32 	%f125, %f124, %f123;
	mul.f32 	%f126, %f8, %f10;
	mul.f32 	%f127, %f7, %f11;
	sub.f32 	%f128, %f127, %f126;
	mul.f32 	%f129, %f2, %f125;
	fma.rn.f32 	%f130, %f1, %f122, %f129;
	fma.rn.f32 	%f131, %f3, %f128, %f130;
	mul.f32 	%f132, %f2, %f8;
	fma.rn.f32 	%f133, %f1, %f7, %f132;
	fma.rn.f32 	%f134, %f3, %f9, %f133;
	add.f32 	%f135, %f134, 0f3F800000;
	mul.f32 	%f136, %f2, %f11;
	fma.rn.f32 	%f137, %f1, %f10, %f136;
	fma.rn.f32 	%f138, %f3, %f12, %f137;
	add.f32 	%f139, %f135, %f138;
	mul.f32 	%f140, %f8, %f11;
	fma.rn.f32 	%f141, %f7, %f10, %f140;
	fma.rn.f32 	%f142, %f9, %f12, %f141;
	add.f32 	%f143, %f142, %f139;
	abs.f32 	%f26, %f143;
	abs.f32 	%f27, %f131;
	setp.eq.f32	%p42, %f26, 0f00000000;
	setp.eq.f32	%p43, %f27, 0f00000000;
	and.pred  	%p44, %p42, %p43;
	mov.b32 	 %r39, %f143;
	mov.b32 	 %r175, %f131;
	and.b32  	%r40, %r175, -2147483648;
	@%p44 bra 	BB0_40;
	bra.uni 	BB0_37;

BB0_40:
	shr.s32 	%r182, %r39, 31;
	and.b32  	%r183, %r182, 1078530011;
	or.b32  	%r184, %r183, %r40;
	mov.b32 	 %f289, %r184;
	bra.uni 	BB0_41;

BB0_37:
	setp.eq.f32	%p45, %f26, 0f7F800000;
	setp.eq.f32	%p46, %f27, 0f7F800000;
	and.pred  	%p47, %p45, %p46;
	@%p47 bra 	BB0_39;
	bra.uni 	BB0_38;

BB0_39:
	shr.s32 	%r178, %r39, 31;
	and.b32  	%r179, %r178, 13483017;
	add.s32 	%r180, %r179, 1061752795;
	or.b32  	%r181, %r180, %r40;
	mov.b32 	 %f289, %r181;
	bra.uni 	BB0_41;

BB0_38:
	max.f32 	%f144, %f27, %f26;
	min.f32 	%f145, %f27, %f26;
	div.rn.f32 	%f146, %f145, %f144;
	mul.rn.f32 	%f147, %f146, %f146;
	mov.f32 	%f148, 0fC0B59883;
	mov.f32 	%f149, 0fBF52C7EA;
	fma.rn.f32 	%f150, %f147, %f149, %f148;
	mov.f32 	%f151, 0fC0D21907;
	fma.rn.f32 	%f152, %f150, %f147, %f151;
	mul.f32 	%f153, %f147, %f152;
	mul.f32 	%f154, %f146, %f153;
	add.f32 	%f155, %f147, 0f41355DC0;
	mov.f32 	%f156, 0f41E6BD60;
	fma.rn.f32 	%f157, %f155, %f147, %f156;
	mov.f32 	%f158, 0f419D92C8;
	fma.rn.f32 	%f159, %f157, %f147, %f158;
	rcp.rn.f32 	%f160, %f159;
	fma.rn.f32 	%f161, %f154, %f160, %f146;
	mov.f32 	%f162, 0f3FC90FDB;
	sub.f32 	%f163, %f162, %f161;
	setp.gt.f32	%p48, %f27, %f26;
	selp.f32	%f164, %f163, %f161, %p48;
	mov.f32 	%f165, 0f40490FDB;
	sub.f32 	%f166, %f165, %f164;
	setp.lt.s32	%p49, %r39, 0;
	selp.f32	%f167, %f166, %f164, %p49;
	mov.b32 	 %r176, %f167;
	or.b32  	%r177, %r176, %r40;
	mov.b32 	 %f168, %r177;
	add.f32 	%f169, %f26, %f27;
	setp.gtu.f32	%p50, %f169, 0f7F800000;
	selp.f32	%f289, %f169, %f168, %p50;

BB0_41:
	add.f32 	%f170, %f289, %f289;
	setp.eq.f32	%p51, %f25, 0f00000000;
	selp.f32	%f171, 0f3F800000, 0f3F000000, %p51;
	fma.rn.f32 	%f290, %f171, %f170, %f290;

BB0_42:
	@!%p1 bra 	BB0_56;
	bra.uni 	BB0_43;

BB0_43:
	setp.lt.s32	%p52, %r21, 0;
	shr.u16 	%rs14, %rs3, 1;
	and.b16  	%rs15, %rs14, 1;
	setp.eq.b16	%p53, %rs15, 1;
	not.pred 	%p54, %p53;
	and.pred  	%p55, %p52, %p54;
	@%p55 bra 	BB0_56;

	@%p9 bra 	BB0_46;

	rem.s32 	%r195, %r21, %r58;
	add.s32 	%r196, %r195, %r58;
	rem.s32 	%r307, %r196, %r58;
	bra.uni 	BB0_47;

BB0_46:
	mov.u32 	%r202, 0;
	max.s32 	%r307, %r21, %r202;

BB0_47:
	setp.eq.b16	%p57, %rs1, 1;
	@!%p57 bra 	BB0_49;
	bra.uni 	BB0_48;

BB0_48:
	rem.s32 	%r208, %r14, %r57;
	add.s32 	%r209, %r208, %r57;
	rem.s32 	%r308, %r209, %r57;
	bra.uni 	BB0_50;

BB0_49:
	mov.u32 	%r215, 0;
	max.s32 	%r308, %r14, %r215;

BB0_50:
	mad.lo.s32 	%r220, %r3, %r58, %r307;
	mad.lo.s32 	%r221, %r220, %r57, %r308;
	mul.wide.s32 	%rd45, %r221, 4;
	add.s64 	%rd46, %rd3, %rd45;
	add.s64 	%rd48, %rd2, %rd45;
	add.s64 	%rd50, %rd1, %rd45;
	ld.global.f32 	%f172, [%rd46];
	ld.global.f32 	%f173, [%rd48];
	mul.f32 	%f174, %f173, %f173;
	fma.rn.f32 	%f175, %f172, %f172, %f174;
	ld.global.f32 	%f176, [%rd50];
	fma.rn.f32 	%f34, %f176, %f176, %f175;
	mul.f32 	%f177, %f12, %f14;
	mul.f32 	%f178, %f11, %f15;
	sub.f32 	%f179, %f178, %f177;
	mul.f32 	%f180, %f10, %f15;
	mul.f32 	%f181, %f12, %f13;
	sub.f32 	%f182, %f181, %f180;
	mul.f32 	%f183, %f11, %f13;
	mul.f32 	%f184, %f10, %f14;
	sub.f32 	%f185, %f184, %f183;
	mul.f32 	%f186, %f2, %f182;
	fma.rn.f32 	%f187, %f1, %f179, %f186;
	fma.rn.f32 	%f188, %f3, %f185, %f187;
	mul.f32 	%f189, %f2, %f11;
	fma.rn.f32 	%f190, %f1, %f10, %f189;
	fma.rn.f32 	%f191, %f3, %f12, %f190;
	add.f32 	%f192, %f191, 0f3F800000;
	mul.f32 	%f193, %f2, %f14;
	fma.rn.f32 	%f194, %f1, %f13, %f193;
	fma.rn.f32 	%f195, %f3, %f15, %f194;
	add.f32 	%f196, %f192, %f195;
	mul.f32 	%f197, %f11, %f14;
	fma.rn.f32 	%f198, %f10, %f13, %f197;
	fma.rn.f32 	%f199, %f12, %f15, %f198;
	add.f32 	%f200, %f199, %f196;
	abs.f32 	%f35, %f200;
	abs.f32 	%f36, %f188;
	setp.eq.f32	%p58, %f35, 0f00000000;
	setp.eq.f32	%p59, %f36, 0f00000000;
	and.pred  	%p60, %p58, %p59;
	mov.b32 	 %r47, %f200;
	mov.b32 	 %r222, %f188;
	and.b32  	%r48, %r222, -2147483648;
	@%p60 bra 	BB0_54;
	bra.uni 	BB0_51;

BB0_54:
	shr.s32 	%r229, %r47, 31;
	and.b32  	%r230, %r229, 1078530011;
	or.b32  	%r231, %r230, %r48;
	mov.b32 	 %f291, %r231;
	bra.uni 	BB0_55;

BB0_51:
	setp.eq.f32	%p61, %f35, 0f7F800000;
	setp.eq.f32	%p62, %f36, 0f7F800000;
	and.pred  	%p63, %p61, %p62;
	@%p63 bra 	BB0_53;
	bra.uni 	BB0_52;

BB0_53:
	shr.s32 	%r225, %r47, 31;
	and.b32  	%r226, %r225, 13483017;
	add.s32 	%r227, %r226, 1061752795;
	or.b32  	%r228, %r227, %r48;
	mov.b32 	 %f291, %r228;
	bra.uni 	BB0_55;

BB0_52:
	max.f32 	%f201, %f36, %f35;
	min.f32 	%f202, %f36, %f35;
	div.rn.f32 	%f203, %f202, %f201;
	mul.rn.f32 	%f204, %f203, %f203;
	mov.f32 	%f205, 0fC0B59883;
	mov.f32 	%f206, 0fBF52C7EA;
	fma.rn.f32 	%f207, %f204, %f206, %f205;
	mov.f32 	%f208, 0fC0D21907;
	fma.rn.f32 	%f209, %f207, %f204, %f208;
	mul.f32 	%f210, %f204, %f209;
	mul.f32 	%f211, %f203, %f210;
	add.f32 	%f212, %f204, 0f41355DC0;
	mov.f32 	%f213, 0f41E6BD60;
	fma.rn.f32 	%f214, %f212, %f204, %f213;
	mov.f32 	%f215, 0f419D92C8;
	fma.rn.f32 	%f216, %f214, %f204, %f215;
	rcp.rn.f32 	%f217, %f216;
	fma.rn.f32 	%f218, %f211, %f217, %f203;
	mov.f32 	%f219, 0f3FC90FDB;
	sub.f32 	%f220, %f219, %f218;
	setp.gt.f32	%p64, %f36, %f35;
	selp.f32	%f221, %f220, %f218, %p64;
	mov.f32 	%f222, 0f40490FDB;
	sub.f32 	%f223, %f222, %f221;
	setp.lt.s32	%p65, %r47, 0;
	selp.f32	%f224, %f223, %f221, %p65;
	mov.b32 	 %r223, %f224;
	or.b32  	%r224, %r223, %r48;
	mov.b32 	 %f225, %r224;
	add.f32 	%f226, %f35, %f36;
	setp.gtu.f32	%p66, %f226, 0f7F800000;
	selp.f32	%f291, %f226, %f225, %p66;

BB0_55:
	add.f32 	%f227, %f291, %f291;
	setp.eq.f32	%p67, %f34, 0f00000000;
	selp.f32	%f228, 0f3F800000, 0f3F000000, %p67;
	fma.rn.f32 	%f290, %f228, %f227, %f290;

BB0_56:
	setp.eq.b16	%p69, %rs1, 1;
	not.pred 	%p70, %p69;
	and.pred  	%p71, %p13, %p70;
	@%p71 bra 	BB0_70;

	setp.lt.s32	%p72, %r21, 0;
	shr.u16 	%rs19, %rs3, 1;
	and.b16  	%rs20, %rs19, 1;
	setp.eq.b16	%p73, %rs20, 1;
	not.pred 	%p74, %p73;
	and.pred  	%p75, %p72, %p74;
	@%p75 bra 	BB0_70;

	@%p9 bra 	BB0_60;

	rem.s32 	%r247, %r21, %r58;
	add.s32 	%r248, %r247, %r58;
	rem.s32 	%r309, %r248, %r58;
	bra.uni 	BB0_61;

BB0_60:
	mov.u32 	%r254, 0;
	max.s32 	%r309, %r21, %r254;

BB0_61:
	setp.eq.b16	%p77, %rs1, 1;
	@!%p77 bra 	BB0_63;
	bra.uni 	BB0_62;

BB0_62:
	rem.s32 	%r260, %r6, %r57;
	add.s32 	%r261, %r260, %r57;
	rem.s32 	%r310, %r261, %r57;
	bra.uni 	BB0_64;

BB0_63:
	add.s32 	%r262, %r57, -1;
	min.s32 	%r310, %r6, %r262;

BB0_64:
	mad.lo.s32 	%r272, %r3, %r58, %r309;
	mad.lo.s32 	%r273, %r272, %r57, %r310;
	mul.wide.s32 	%rd52, %r273, 4;
	add.s64 	%rd53, %rd3, %rd52;
	add.s64 	%rd55, %rd2, %rd52;
	add.s64 	%rd57, %rd1, %rd52;
	ld.global.f32 	%f229, [%rd53];
	ld.global.f32 	%f230, [%rd55];
	mul.f32 	%f231, %f230, %f230;
	fma.rn.f32 	%f232, %f229, %f229, %f231;
	ld.global.f32 	%f233, [%rd57];
	fma.rn.f32 	%f43, %f233, %f233, %f232;
	mul.f32 	%f234, %f5, %f15;
	mul.f32 	%f235, %f6, %f14;
	sub.f32 	%f236, %f235, %f234;
	mul.f32 	%f237, %f6, %f13;
	mul.f32 	%f238, %f4, %f15;
	sub.f32 	%f239, %f238, %f237;
	mul.f32 	%f240, %f4, %f14;
	mul.f32 	%f241, %f5, %f13;
	sub.f32 	%f242, %f241, %f240;
	mul.f32 	%f243, %f2, %f239;
	fma.rn.f32 	%f244, %f1, %f236, %f243;
	fma.rn.f32 	%f245, %f3, %f242, %f244;
	mul.f32 	%f246, %f2, %f14;
	fma.rn.f32 	%f247, %f1, %f13, %f246;
	fma.rn.f32 	%f248, %f3, %f15, %f247;
	add.f32 	%f249, %f248, 0f3F800000;
	mul.f32 	%f250, %f2, %f5;
	fma.rn.f32 	%f251, %f1, %f4, %f250;
	fma.rn.f32 	%f252, %f3, %f6, %f251;
	add.f32 	%f253, %f252, %f249;
	mul.f32 	%f254, %f5, %f14;
	fma.rn.f32 	%f255, %f4, %f13, %f254;
	fma.rn.f32 	%f256, %f6, %f15, %f255;
	add.f32 	%f257, %f256, %f253;
	abs.f32 	%f44, %f257;
	abs.f32 	%f45, %f245;
	setp.eq.f32	%p78, %f44, 0f00000000;
	setp.eq.f32	%p79, %f45, 0f00000000;
	and.pred  	%p80, %p78, %p79;
	mov.b32 	 %r55, %f257;
	mov.b32 	 %r274, %f245;
	and.b32  	%r56, %r274, -2147483648;
	@%p80 bra 	BB0_68;
	bra.uni 	BB0_65;

BB0_68:
	shr.s32 	%r281, %r55, 31;
	and.b32  	%r282, %r281, 1078530011;
	or.b32  	%r283, %r282, %r56;
	mov.b32 	 %f293, %r283;
	bra.uni 	BB0_69;

BB0_65:
	setp.eq.f32	%p81, %f44, 0f7F800000;
	setp.eq.f32	%p82, %f45, 0f7F800000;
	and.pred  	%p83, %p81, %p82;
	@%p83 bra 	BB0_67;
	bra.uni 	BB0_66;

BB0_67:
	shr.s32 	%r277, %r55, 31;
	and.b32  	%r278, %r277, 13483017;
	add.s32 	%r279, %r278, 1061752795;
	or.b32  	%r280, %r279, %r56;
	mov.b32 	 %f293, %r280;
	bra.uni 	BB0_69;

BB0_66:
	max.f32 	%f258, %f45, %f44;
	min.f32 	%f259, %f45, %f44;
	div.rn.f32 	%f260, %f259, %f258;
	mul.rn.f32 	%f261, %f260, %f260;
	mov.f32 	%f262, 0fC0B59883;
	mov.f32 	%f263, 0fBF52C7EA;
	fma.rn.f32 	%f264, %f261, %f263, %f262;
	mov.f32 	%f265, 0fC0D21907;
	fma.rn.f32 	%f266, %f264, %f261, %f265;
	mul.f32 	%f267, %f261, %f266;
	mul.f32 	%f268, %f260, %f267;
	add.f32 	%f269, %f261, 0f41355DC0;
	mov.f32 	%f270, 0f41E6BD60;
	fma.rn.f32 	%f271, %f269, %f261, %f270;
	mov.f32 	%f272, 0f419D92C8;
	fma.rn.f32 	%f273, %f271, %f261, %f272;
	rcp.rn.f32 	%f274, %f273;
	fma.rn.f32 	%f275, %f268, %f274, %f260;
	mov.f32 	%f276, 0f3FC90FDB;
	sub.f32 	%f277, %f276, %f275;
	setp.gt.f32	%p84, %f45, %f44;
	selp.f32	%f278, %f277, %f275, %p84;
	mov.f32 	%f279, 0f40490FDB;
	sub.f32 	%f280, %f279, %f278;
	setp.lt.s32	%p85, %r55, 0;
	selp.f32	%f281, %f280, %f278, %p85;
	mov.b32 	 %r275, %f281;
	or.b32  	%r276, %r275, %r56;
	mov.b32 	 %f282, %r276;
	add.f32 	%f283, %f44, %f45;
	setp.gtu.f32	%p86, %f283, 0f7F800000;
	selp.f32	%f293, %f283, %f282, %p86;

BB0_69:
	add.f32 	%f284, %f293, %f293;
	setp.eq.f32	%p87, %f43, 0f00000000;
	selp.f32	%f285, 0f3F800000, 0f3F000000, %p87;
	fma.rn.f32 	%f290, %f285, %f284, %f290;

BB0_70:
	mad.lo.s32 	%r292, %r3, %r58, %r2;
	mad.lo.s32 	%r297, %r292, %r57, %r1;
	mul.wide.s32 	%rd59, %r297, 4;
	add.s64 	%rd60, %rd9, %rd59;
	mul.f32 	%f286, %f290, %f52;
	st.global.f32 	[%rd60], %f286;

BB0_72:
	ret;
}


`
)
