package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for addtriaxialanisotropy2 kernel
var addtriaxialanisotropy2_code cu.Function

// Stores the arguments for addtriaxialanisotropy2 kernel invocation
type addtriaxialanisotropy2_args_t struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_Ms_     unsafe.Pointer
	arg_Ms_mul  float32
	arg_k1_     unsafe.Pointer
	arg_k1_mul  float32
	arg_k2_     unsafe.Pointer
	arg_k2_mul  float32
	arg_k3_     unsafe.Pointer
	arg_k3_mul  float32
	arg_c1x_    unsafe.Pointer
	arg_c1x_mul float32
	arg_c1y_    unsafe.Pointer
	arg_c1y_mul float32
	arg_c1z_    unsafe.Pointer
	arg_c1z_mul float32
	arg_c2x_    unsafe.Pointer
	arg_c2x_mul float32
	arg_c2y_    unsafe.Pointer
	arg_c2y_mul float32
	arg_c2z_    unsafe.Pointer
	arg_c2z_mul float32
	arg_c3x_    unsafe.Pointer
	arg_c3x_mul float32
	arg_c3y_    unsafe.Pointer
	arg_c3y_mul float32
	arg_c3z_    unsafe.Pointer
	arg_c3z_mul float32
	arg_N       int
	argptr      [33]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addtriaxialanisotropy2 kernel invocation
var addtriaxialanisotropy2_args addtriaxialanisotropy2_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addtriaxialanisotropy2_args.argptr[0] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_Bx)
	addtriaxialanisotropy2_args.argptr[1] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_By)
	addtriaxialanisotropy2_args.argptr[2] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_Bz)
	addtriaxialanisotropy2_args.argptr[3] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_mx)
	addtriaxialanisotropy2_args.argptr[4] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_my)
	addtriaxialanisotropy2_args.argptr[5] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_mz)
	addtriaxialanisotropy2_args.argptr[6] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_Ms_)
	addtriaxialanisotropy2_args.argptr[7] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_Ms_mul)
	addtriaxialanisotropy2_args.argptr[8] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k1_)
	addtriaxialanisotropy2_args.argptr[9] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k1_mul)
	addtriaxialanisotropy2_args.argptr[10] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k2_)
	addtriaxialanisotropy2_args.argptr[11] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k2_mul)
	addtriaxialanisotropy2_args.argptr[12] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k3_)
	addtriaxialanisotropy2_args.argptr[13] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_k3_mul)
	addtriaxialanisotropy2_args.argptr[14] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1x_)
	addtriaxialanisotropy2_args.argptr[15] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1x_mul)
	addtriaxialanisotropy2_args.argptr[16] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1y_)
	addtriaxialanisotropy2_args.argptr[17] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1y_mul)
	addtriaxialanisotropy2_args.argptr[18] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1z_)
	addtriaxialanisotropy2_args.argptr[19] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c1z_mul)
	addtriaxialanisotropy2_args.argptr[20] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2x_)
	addtriaxialanisotropy2_args.argptr[21] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2x_mul)
	addtriaxialanisotropy2_args.argptr[22] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2y_)
	addtriaxialanisotropy2_args.argptr[23] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2y_mul)
	addtriaxialanisotropy2_args.argptr[24] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2z_)
	addtriaxialanisotropy2_args.argptr[25] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c2z_mul)
	addtriaxialanisotropy2_args.argptr[26] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3x_)
	addtriaxialanisotropy2_args.argptr[27] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3x_mul)
	addtriaxialanisotropy2_args.argptr[28] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3y_)
	addtriaxialanisotropy2_args.argptr[29] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3y_mul)
	addtriaxialanisotropy2_args.argptr[30] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3z_)
	addtriaxialanisotropy2_args.argptr[31] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_c3z_mul)
	addtriaxialanisotropy2_args.argptr[32] = unsafe.Pointer(&addtriaxialanisotropy2_args.arg_N)
}

// Wrapper for addtriaxialanisotropy2 CUDA kernel, asynchronous.
func k_addtriaxialanisotropy2_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, k1_ unsafe.Pointer, k1_mul float32, k2_ unsafe.Pointer, k2_mul float32, k3_ unsafe.Pointer, k3_mul float32, c1x_ unsafe.Pointer, c1x_mul float32, c1y_ unsafe.Pointer, c1y_mul float32, c1z_ unsafe.Pointer, c1z_mul float32, c2x_ unsafe.Pointer, c2x_mul float32, c2y_ unsafe.Pointer, c2y_mul float32, c2z_ unsafe.Pointer, c2z_mul float32, c3x_ unsafe.Pointer, c3x_mul float32, c3y_ unsafe.Pointer, c3y_mul float32, c3z_ unsafe.Pointer, c3z_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addtriaxialanisotropy2")
	}

	addtriaxialanisotropy2_args.Lock()
	defer addtriaxialanisotropy2_args.Unlock()

	if addtriaxialanisotropy2_code == 0 {
		addtriaxialanisotropy2_code = fatbinLoad(addtriaxialanisotropy2_map, "addtriaxialanisotropy2")
	}

	addtriaxialanisotropy2_args.arg_Bx = Bx
	addtriaxialanisotropy2_args.arg_By = By
	addtriaxialanisotropy2_args.arg_Bz = Bz
	addtriaxialanisotropy2_args.arg_mx = mx
	addtriaxialanisotropy2_args.arg_my = my
	addtriaxialanisotropy2_args.arg_mz = mz
	addtriaxialanisotropy2_args.arg_Ms_ = Ms_
	addtriaxialanisotropy2_args.arg_Ms_mul = Ms_mul
	addtriaxialanisotropy2_args.arg_k1_ = k1_
	addtriaxialanisotropy2_args.arg_k1_mul = k1_mul
	addtriaxialanisotropy2_args.arg_k2_ = k2_
	addtriaxialanisotropy2_args.arg_k2_mul = k2_mul
	addtriaxialanisotropy2_args.arg_k3_ = k3_
	addtriaxialanisotropy2_args.arg_k3_mul = k3_mul
	addtriaxialanisotropy2_args.arg_c1x_ = c1x_
	addtriaxialanisotropy2_args.arg_c1x_mul = c1x_mul
	addtriaxialanisotropy2_args.arg_c1y_ = c1y_
	addtriaxialanisotropy2_args.arg_c1y_mul = c1y_mul
	addtriaxialanisotropy2_args.arg_c1z_ = c1z_
	addtriaxialanisotropy2_args.arg_c1z_mul = c1z_mul
	addtriaxialanisotropy2_args.arg_c2x_ = c2x_
	addtriaxialanisotropy2_args.arg_c2x_mul = c2x_mul
	addtriaxialanisotropy2_args.arg_c2y_ = c2y_
	addtriaxialanisotropy2_args.arg_c2y_mul = c2y_mul
	addtriaxialanisotropy2_args.arg_c2z_ = c2z_
	addtriaxialanisotropy2_args.arg_c2z_mul = c2z_mul
	addtriaxialanisotropy2_args.arg_c3x_ = c3x_
	addtriaxialanisotropy2_args.arg_c3x_mul = c3x_mul
	addtriaxialanisotropy2_args.arg_c3y_ = c3y_
	addtriaxialanisotropy2_args.arg_c3y_mul = c3y_mul
	addtriaxialanisotropy2_args.arg_c3z_ = c3z_
	addtriaxialanisotropy2_args.arg_c3z_mul = c3z_mul
	addtriaxialanisotropy2_args.arg_N = N

	args := addtriaxialanisotropy2_args.argptr[:]
	cu.LaunchKernel(addtriaxialanisotropy2_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addtriaxialanisotropy2")
	}
}

// maps compute capability on PTX code for addtriaxialanisotropy2 kernel.
var addtriaxialanisotropy2_map = map[int]string{0: "",
	61: addtriaxialanisotropy2_ptx_61}

// addtriaxialanisotropy2 PTX code for various compute capabilities.
const (
	addtriaxialanisotropy2_ptx_61 = `
.version 7.1
.target sm_61
.address_size 64

	// .globl	addtriaxialanisotropy2

.visible .entry addtriaxialanisotropy2(
	.param .u64 addtriaxialanisotropy2_param_0,
	.param .u64 addtriaxialanisotropy2_param_1,
	.param .u64 addtriaxialanisotropy2_param_2,
	.param .u64 addtriaxialanisotropy2_param_3,
	.param .u64 addtriaxialanisotropy2_param_4,
	.param .u64 addtriaxialanisotropy2_param_5,
	.param .u64 addtriaxialanisotropy2_param_6,
	.param .f32 addtriaxialanisotropy2_param_7,
	.param .u64 addtriaxialanisotropy2_param_8,
	.param .f32 addtriaxialanisotropy2_param_9,
	.param .u64 addtriaxialanisotropy2_param_10,
	.param .f32 addtriaxialanisotropy2_param_11,
	.param .u64 addtriaxialanisotropy2_param_12,
	.param .f32 addtriaxialanisotropy2_param_13,
	.param .u64 addtriaxialanisotropy2_param_14,
	.param .f32 addtriaxialanisotropy2_param_15,
	.param .u64 addtriaxialanisotropy2_param_16,
	.param .f32 addtriaxialanisotropy2_param_17,
	.param .u64 addtriaxialanisotropy2_param_18,
	.param .f32 addtriaxialanisotropy2_param_19,
	.param .u64 addtriaxialanisotropy2_param_20,
	.param .f32 addtriaxialanisotropy2_param_21,
	.param .u64 addtriaxialanisotropy2_param_22,
	.param .f32 addtriaxialanisotropy2_param_23,
	.param .u64 addtriaxialanisotropy2_param_24,
	.param .f32 addtriaxialanisotropy2_param_25,
	.param .u64 addtriaxialanisotropy2_param_26,
	.param .f32 addtriaxialanisotropy2_param_27,
	.param .u64 addtriaxialanisotropy2_param_28,
	.param .f32 addtriaxialanisotropy2_param_29,
	.param .u64 addtriaxialanisotropy2_param_30,
	.param .f32 addtriaxialanisotropy2_param_31,
	.param .u32 addtriaxialanisotropy2_param_32
)
{
	.reg .pred 	%p<19>;
	.reg .f32 	%f<139>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<72>;


	ld.param.u64 	%rd1, [addtriaxialanisotropy2_param_0];
	ld.param.u64 	%rd2, [addtriaxialanisotropy2_param_1];
	ld.param.u64 	%rd3, [addtriaxialanisotropy2_param_2];
	ld.param.u64 	%rd4, [addtriaxialanisotropy2_param_3];
	ld.param.u64 	%rd5, [addtriaxialanisotropy2_param_4];
	ld.param.u64 	%rd6, [addtriaxialanisotropy2_param_5];
	ld.param.u64 	%rd7, [addtriaxialanisotropy2_param_6];
	ld.param.f32 	%f122, [addtriaxialanisotropy2_param_7];
	ld.param.u64 	%rd8, [addtriaxialanisotropy2_param_8];
	ld.param.f32 	%f124, [addtriaxialanisotropy2_param_9];
	ld.param.u64 	%rd9, [addtriaxialanisotropy2_param_10];
	ld.param.f32 	%f125, [addtriaxialanisotropy2_param_11];
	ld.param.u64 	%rd10, [addtriaxialanisotropy2_param_12];
	ld.param.f32 	%f126, [addtriaxialanisotropy2_param_13];
	ld.param.u64 	%rd11, [addtriaxialanisotropy2_param_14];
	ld.param.f32 	%f127, [addtriaxialanisotropy2_param_15];
	ld.param.u64 	%rd12, [addtriaxialanisotropy2_param_16];
	ld.param.f32 	%f128, [addtriaxialanisotropy2_param_17];
	ld.param.u64 	%rd13, [addtriaxialanisotropy2_param_18];
	ld.param.f32 	%f129, [addtriaxialanisotropy2_param_19];
	ld.param.u64 	%rd14, [addtriaxialanisotropy2_param_20];
	ld.param.f32 	%f131, [addtriaxialanisotropy2_param_21];
	ld.param.u64 	%rd15, [addtriaxialanisotropy2_param_22];
	ld.param.f32 	%f132, [addtriaxialanisotropy2_param_23];
	ld.param.u64 	%rd16, [addtriaxialanisotropy2_param_24];
	ld.param.f32 	%f133, [addtriaxialanisotropy2_param_25];
	ld.param.u64 	%rd17, [addtriaxialanisotropy2_param_26];
	ld.param.f32 	%f135, [addtriaxialanisotropy2_param_27];
	ld.param.u64 	%rd18, [addtriaxialanisotropy2_param_28];
	ld.param.f32 	%f136, [addtriaxialanisotropy2_param_29];
	ld.param.u64 	%rd19, [addtriaxialanisotropy2_param_30];
	ld.param.f32 	%f137, [addtriaxialanisotropy2_param_31];
	ld.param.u32 	%r2, [addtriaxialanisotropy2_param_32];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_36;

	setp.eq.s64	%p2, %rd7, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd20, %rd7;
	mul.wide.s32 	%rd21, %r1, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.nc.f32 	%f60, [%rd22];
	mul.f32 	%f122, %f60, %f122;

BB0_3:
	setp.eq.f32	%p3, %f122, 0f00000000;
	mov.f32 	%f123, 0f00000000;
	@%p3 bra 	BB0_5;

	rcp.rn.f32 	%f123, %f122;

BB0_5:
	setp.eq.s64	%p4, %rd8, 0;
	@%p4 bra 	BB0_7;

	cvta.to.global.u64 	%rd23, %rd8;
	mul.wide.s32 	%rd24, %r1, 4;
	add.s64 	%rd25, %rd23, %rd24;
	ld.global.nc.f32 	%f62, [%rd25];
	mul.f32 	%f124, %f62, %f124;

BB0_7:
	setp.eq.s64	%p5, %rd9, 0;
	@%p5 bra 	BB0_9;

	cvta.to.global.u64 	%rd26, %rd9;
	mul.wide.s32 	%rd27, %r1, 4;
	add.s64 	%rd28, %rd26, %rd27;
	ld.global.nc.f32 	%f63, [%rd28];
	mul.f32 	%f125, %f63, %f125;

BB0_9:
	setp.eq.s64	%p6, %rd10, 0;
	@%p6 bra 	BB0_11;

	cvta.to.global.u64 	%rd29, %rd10;
	mul.wide.s32 	%rd30, %r1, 4;
	add.s64 	%rd31, %rd29, %rd30;
	ld.global.nc.f32 	%f64, [%rd31];
	mul.f32 	%f126, %f64, %f126;

BB0_11:
	mul.f32 	%f11, %f123, %f126;
	setp.eq.s64	%p7, %rd11, 0;
	mul.f32 	%f12, %f123, %f124;
	mul.f32 	%f13, %f123, %f125;
	@%p7 bra 	BB0_13;

	cvta.to.global.u64 	%rd32, %rd11;
	mul.wide.s32 	%rd33, %r1, 4;
	add.s64 	%rd34, %rd32, %rd33;
	ld.global.nc.f32 	%f65, [%rd34];
	mul.f32 	%f127, %f65, %f127;

BB0_13:
	setp.eq.s64	%p8, %rd12, 0;
	@%p8 bra 	BB0_15;

	cvta.to.global.u64 	%rd35, %rd12;
	mul.wide.s32 	%rd36, %r1, 4;
	add.s64 	%rd37, %rd35, %rd36;
	ld.global.nc.f32 	%f66, [%rd37];
	mul.f32 	%f128, %f66, %f128;

BB0_15:
	setp.eq.s64	%p9, %rd13, 0;
	@%p9 bra 	BB0_17;

	cvta.to.global.u64 	%rd38, %rd13;
	mul.wide.s32 	%rd39, %r1, 4;
	add.s64 	%rd40, %rd38, %rd39;
	ld.global.nc.f32 	%f67, [%rd40];
	mul.f32 	%f129, %f67, %f129;

BB0_17:
	mul.f32 	%f69, %f128, %f128;
	fma.rn.f32 	%f70, %f127, %f127, %f69;
	fma.rn.f32 	%f71, %f129, %f129, %f70;
	sqrt.rn.f32 	%f20, %f71;
	mov.f32 	%f130, 0f00000000;
	setp.eq.f32	%p10, %f20, 0f00000000;
	@%p10 bra 	BB0_19;

	rcp.rn.f32 	%f130, %f20;

BB0_19:
	mul.f32 	%f23, %f127, %f130;
	mul.f32 	%f24, %f128, %f130;
	mul.f32 	%f25, %f129, %f130;
	setp.eq.s64	%p11, %rd14, 0;
	@%p11 bra 	BB0_21;

	cvta.to.global.u64 	%rd41, %rd14;
	mul.wide.s32 	%rd42, %r1, 4;
	add.s64 	%rd43, %rd41, %rd42;
	ld.global.nc.f32 	%f72, [%rd43];
	mul.f32 	%f131, %f72, %f131;

BB0_21:
	setp.eq.s64	%p12, %rd15, 0;
	@%p12 bra 	BB0_23;

	cvta.to.global.u64 	%rd44, %rd15;
	mul.wide.s32 	%rd45, %r1, 4;
	add.s64 	%rd46, %rd44, %rd45;
	ld.global.nc.f32 	%f73, [%rd46];
	mul.f32 	%f132, %f73, %f132;

BB0_23:
	setp.eq.s64	%p13, %rd16, 0;
	@%p13 bra 	BB0_25;

	cvta.to.global.u64 	%rd47, %rd16;
	mul.wide.s32 	%rd48, %r1, 4;
	add.s64 	%rd49, %rd47, %rd48;
	ld.global.nc.f32 	%f74, [%rd49];
	mul.f32 	%f133, %f74, %f133;

BB0_25:
	mul.f32 	%f76, %f132, %f132;
	fma.rn.f32 	%f77, %f131, %f131, %f76;
	fma.rn.f32 	%f78, %f133, %f133, %f77;
	sqrt.rn.f32 	%f32, %f78;
	mov.f32 	%f134, 0f00000000;
	setp.eq.f32	%p14, %f32, 0f00000000;
	@%p14 bra 	BB0_27;

	rcp.rn.f32 	%f134, %f32;

BB0_27:
	mul.f32 	%f35, %f131, %f134;
	mul.f32 	%f36, %f132, %f134;
	mul.f32 	%f37, %f133, %f134;
	setp.eq.s64	%p15, %rd17, 0;
	@%p15 bra 	BB0_29;

	cvta.to.global.u64 	%rd50, %rd17;
	mul.wide.s32 	%rd51, %r1, 4;
	add.s64 	%rd52, %rd50, %rd51;
	ld.global.nc.f32 	%f79, [%rd52];
	mul.f32 	%f135, %f79, %f135;

BB0_29:
	setp.eq.s64	%p16, %rd18, 0;
	@%p16 bra 	BB0_31;

	cvta.to.global.u64 	%rd53, %rd18;
	mul.wide.s32 	%rd54, %r1, 4;
	add.s64 	%rd55, %rd53, %rd54;
	ld.global.nc.f32 	%f80, [%rd55];
	mul.f32 	%f136, %f80, %f136;

BB0_31:
	setp.eq.s64	%p17, %rd19, 0;
	@%p17 bra 	BB0_33;

	cvta.to.global.u64 	%rd56, %rd19;
	mul.wide.s32 	%rd57, %r1, 4;
	add.s64 	%rd58, %rd56, %rd57;
	ld.global.nc.f32 	%f81, [%rd58];
	mul.f32 	%f137, %f81, %f137;

BB0_33:
	mul.f32 	%f83, %f136, %f136;
	fma.rn.f32 	%f84, %f135, %f135, %f83;
	fma.rn.f32 	%f85, %f137, %f137, %f84;
	sqrt.rn.f32 	%f44, %f85;
	mov.f32 	%f138, 0f00000000;
	setp.eq.f32	%p18, %f44, 0f00000000;
	@%p18 bra 	BB0_35;

	rcp.rn.f32 	%f138, %f44;

BB0_35:
	cvta.to.global.u64 	%rd59, %rd4;
	mul.wide.s32 	%rd60, %r1, 4;
	add.s64 	%rd61, %rd59, %rd60;
	cvta.to.global.u64 	%rd62, %rd5;
	add.s64 	%rd63, %rd62, %rd60;
	cvta.to.global.u64 	%rd64, %rd6;
	add.s64 	%rd65, %rd64, %rd60;
	ld.global.nc.f32 	%f86, [%rd61];
	ld.global.nc.f32 	%f87, [%rd63];
	mul.f32 	%f88, %f24, %f87;
	fma.rn.f32 	%f89, %f23, %f86, %f88;
	ld.global.nc.f32 	%f90, [%rd65];
	fma.rn.f32 	%f91, %f25, %f90, %f89;
	mul.f32 	%f92, %f36, %f87;
	fma.rn.f32 	%f93, %f35, %f86, %f92;
	fma.rn.f32 	%f94, %f37, %f90, %f93;
	mul.f32 	%f95, %f135, %f138;
	mul.f32 	%f96, %f136, %f138;
	mul.f32 	%f97, %f96, %f87;
	fma.rn.f32 	%f98, %f95, %f86, %f97;
	mul.f32 	%f99, %f137, %f138;
	fma.rn.f32 	%f100, %f99, %f90, %f98;
	add.f32 	%f101, %f12, %f12;
	mul.f32 	%f102, %f101, %f91;
	add.f32 	%f103, %f13, %f13;
	mul.f32 	%f104, %f103, %f94;
	mul.f32 	%f105, %f35, %f104;
	mul.f32 	%f106, %f36, %f104;
	mul.f32 	%f107, %f37, %f104;
	fma.rn.f32 	%f108, %f23, %f102, %f105;
	fma.rn.f32 	%f109, %f24, %f102, %f106;
	fma.rn.f32 	%f110, %f25, %f102, %f107;
	add.f32 	%f111, %f11, %f11;
	mul.f32 	%f112, %f111, %f100;
	fma.rn.f32 	%f113, %f95, %f112, %f108;
	fma.rn.f32 	%f114, %f96, %f112, %f109;
	fma.rn.f32 	%f115, %f99, %f112, %f110;
	cvta.to.global.u64 	%rd66, %rd1;
	add.s64 	%rd67, %rd66, %rd60;
	ld.global.f32 	%f116, [%rd67];
	add.f32 	%f117, %f116, %f113;
	st.global.f32 	[%rd67], %f117;
	cvta.to.global.u64 	%rd68, %rd2;
	add.s64 	%rd69, %rd68, %rd60;
	ld.global.f32 	%f118, [%rd69];
	add.f32 	%f119, %f118, %f114;
	st.global.f32 	[%rd69], %f119;
	cvta.to.global.u64 	%rd70, %rd3;
	add.s64 	%rd71, %rd70, %rd60;
	ld.global.f32 	%f120, [%rd71];
	add.f32 	%f121, %f120, %f115;
	st.global.f32 	[%rd71], %f121;

BB0_36:
	ret;
}


`
)
